
welcome_message = "Введите пароль для начала работы с ботом."
wrong_keyword = "Вы ввели неверный пароль, попробуйте ещё раз."
right_keyword = "Код принят"
createpoll_is_anonymous = "Будет ли опрос анонимным?"
createpoll_question = "Введите вопрос для опроса"
createpoll_allows_multiple_answers = "Разрешено ли выбирать несколько вариантов ответа?"
createpoll_answers = "Введите вариант ответа."
createpoll_answers_1 = "Вариант ответа сохранен, введите еще один"
createpoll_answers_2 = "Вариант ответа сохранен, вы можете добавить еще вариант ответа или закончить"
createpoll_expire_time = ""